apiVersion: v1
kind: Service
metadata:
  name: fccaller
  labels:
          run: fccaller
spec:
  type: NodePort
  ports:
  - port: 8544
    targetPort: 8544
  selector:
          run: fccaller

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fccaller
  labels:
    app: fccaller
spec:
  replicas: 1
  selector:
          matchLabels:
                  run: fccaller
  template:
    metadata:
      labels:
        run: fccaller
    spec:
      containers:
      - name: fccaller
        image: fccaller:0.1.1  
        ports:
        - containerPort: 8544
        imagePullPolicy: IfNotPresent
