FROM openjdk:8-jdk-alpine
EXPOSE 8543
ARG JAR_FILE=target/fcbasesvc-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} fcbasesvc-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","fcbasesvc-0.0.1-SNAPSHOT.jar"]
