FROM openjdk:8-jdk-alpine
EXPOSE 8544
ARG JAR_FILE=target/fccallersvc-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} fccallersvc-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","fccallersvc-0.0.1-SNAPSHOT.jar"]
